### ISSUE TITLE
Can't launch game

### ISSUE THREAD

**Issue by saphirerose** [wideblaze/DigSite#28]
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

When it opens the launcher from twitch and I click play, it shows me this under game output. 
Thank you for any help

**Comment by saphirerose** [comment]
I figured out I needed to update the Java version in my twitch minecraft settings
